# Generated by Django 4.2 on 2023-06-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='Modified')),
                ('operation', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id operation')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.operationtype', verbose_name='Operation Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Operation register',
                'verbose_name_plural': 'Operations register',
            },
        ),
    ]
